# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d952af643b1d46ea56a3a0af3c1f12783dac063ea0bdf694833c1421e0d8fcfbf71444a5ee9b5fb3c1d47f2a387969f10718109c644210a9efafdfdf94ebcd5b

test:
  secret_key_base: ce6067cd46f550d82d508e0bac4afd7a9b6d7ed617b829397828a6886decff884f4a2209e9ea2b3f6a66cac77b97cbfe063e56fafae4098d8d3caba72b6b2e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
